services:
    apnet.assetic.importer.jquery:
        parent: assetic.importer_pre
        arguments:
            - %kernel.root_dir%/Resources/assets/jquery-source.yml
            - jquery
        tags:
            - { name: apnet.assetic.config_mapper, watcher: pre }
